### ISSUE TITLE
编译demo出错

### ISSUE THREAD

**Issue by kukutt** [AXERA-TECH/ax650n_bsp_sdk#1]
提示
/home/ubuntu/maixbox/ax650n_bsp_sdk/app/demo/src/ppl/box/box_ppl/BoxBuilder.hpp:25:10: fatal error: linker.hpp: No such file or directory
   25 | #include "linker.hpp"

**Comment by BUG1989** [comment]
- 已更新至 1.45
- 补充上必要的文件，同时添加了 CI 保证 100% 能编译成功 app 和 msp/sample

**Comment by ytsi** [comment]
skelModels 模型如何训练？
yolov5s训练的模型无法直接使用

**Comment by LRuiRui517** [comment]
> * 已更新至 1.45
> * 补充上必要的文件，同时添加了 CI 保证 100% 能编译成功 app 和 msp/sample

box.conf里面没有检测模型，请问如何使用检测模型检测之后在输出到屏幕上呢？
